#!/bin/bash
export LC_ALL=C.UTF-8
export LANG=C.UTF-8

logo_sonda_script() {
echo -e "${LB}    SONDA v$(cat $VERSION/current) (SysNet release) by @yonasuriv. Type -h to view the complete list of commands." | lolcat
}

logo_sonda_sysnet() {
source $STATIC/art/syssonda_wide | lolcat
}


# logo_sonda_sysnet_isom4() {
#   echo -e """

#   """ | lolcat
# }

# Generate a random number between 0 and 3
# random_choice=$(( RANDOM % 4 ))

# # Choose one of the 4 variables based on the random number
# case $random_choice in
#     0)
#         source $STATIC/art/isometric1.sh | lolcat
#         ;;
#     1)
#         source $STATIC/art/isometric2.sh | lolcat
#         ;;
#     2)
#         source $STATIC/art/isometric3.sh | lolcat
#         ;;
#     3)
#         source $STATIC/art/isometric4.sh | lolcat
#         ;;
# esac