#!/bin/bash

# Parse arguments before checking the value of LOCAL
while [ $# -gt 0 ]; do
  case "$1" in
      --local)
          LOCAL="YES"
          shift 1 # Only shift 1 argument here since --local has no extra argument
          continue
          ;;
      *)
          echo -e "${LB}${RED} [E] Invalid Argument"
          exit 1
          ;;
  esac
done

# Now check the value of LOCAL
if [[ "$LOCAL" == "YES" ]]; then
    INSTALLDIR="$(pwd)"
else
    INSTALLDIR="/usr/share/sysdd"
fi

# Script init
set -a
MODDIR="$INSTALLDIR/modules/functions"
MODHEL="$INSTALLDIR/modules/functions/info"
MODLST="$INSTALLDIR/modules/functions/list"
MODCOR="$INSTALLDIR/modules/functions/core"

STYLE="$INSTALLDIR/modules/style"
HELPER="$INSTALLDIR/modules/helper"
FUNCTIONS="$INSTALLDIR/modules/functions"
set +x

source $STYLE/colors
source $HELPER/top

source $MODCOR/sys_main
source $MODCOR/sys_check
source $MODLST/installed_packages
source $MODHEL/info_networks
source $MODHEL/info_devices
source $MODHEL/info_gpu
source $MODHEL/info_disks
source $MODHEL/info_sys
source $MODHEL/info_cpu
source $MODHEL/info_kernel
source $MODHEL/info_battery

source $HELPER/args