#!/bin/bash

# SysNet/Sonda installation script
# Created by @yonasuriv

source lib/includes/colors

# Define variables
REPO_URL="https://github.com/yonasuriv/sonda"
SHARED_DIR="/usr/share/sonda"
BIN_DIR="/usr/bin"
BIN_NAME="sonda"
BIN_LOCALNAME="init"
BIN_LOCALPATH="$SHARED_DIR/bin/$BIN_LOCALNAME"

# Ensure the script is run with sudo/root permissions
if sudo -n true 2>/dev/null; then
    :
else
    echo -ne "${LB}${RED}[E]${RT} This script must be run as root. Please enter your "; sudo -v || { echo -e "${RED}[E]${RT} Operation cancelled."; exit 1; }
fi

sudo mkdir -p $SHARED_DIR
sudo cp -rf "$(pwd)"/* "$SHARED_DIR"
sudo cp -r $BIN_LOCALPATH $BIN_DIR/$BIN_NAME || { echo -e "${RED}[E]${RT} Failed to copy binary to /usr/bin."; exit 1; }
sudo cp -f static/shortcuts/sonda.desktop /usr/share/applications/sonda.desktop

sudo chmod 644 /usr/share/sonda/static/icons/sonda.png
sudo chmod +x $BIN_DIR/$BIN_NAME

sudo apt install -y lolcat inxi > /dev/null 2>&1

echo -e "${LB}${GREEN} ✔ ${RT} Installation completed. You can now run 'sonda' from the terminal."